sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
before_script:
  - npm i
  - mkdir -p dist/lib/ dist/test/
  - node_modules/.bin/babel src/index.js --out-file dist/lib/index.js
  - node_modules/.bin/babel test/test.js --out-file dist/test/test.js
  - node_modules/.bin/mocha dist/test/test.js
